### ISSUE TITLE
Lock down the version of `syncpack` to avoid breaking changes

### ISSUE THREAD

**Issue by zFernand0** [zowe-actions/octorelease#103]
If the syncpack package is not part of the project dependencies, we might want to lock it down to a version where the specified options always work 😋 
https://github.com/zowe-actions/octorelease/blob/6796f97a067997f0c2fd29dfa6b21aec03ebe8d6/packages/run-script/scripts/npmUpdate.ts#L111-L112

This workflow might help illustrate the issue:
- https://github.com/zFernand0/cics-for-zowe-client/actions/runs/5812912463/job/15759332575

**Comment by t1m0thyj** [comment]
We should probably also lock down the version of lerna to v6 so that we don't have to install it in our pipelines 😋 
https://github.com/zowe/vscode-extension-for-zowe/blob/main/.github/workflows/deployment.yml#L38

**Comment by t1m0thyj** [comment]
Plan to lock down syncpack to v8 (known working version that supports pnpm overrides). Not planning to lock down lerna, if no version is already installed then we should probably use latest which is current behavior.
