### ISSUE TITLE
`update` verb could create a patch release

### ISSUE THREAD

**Issue by zFernand0** [zowe-actions/octorelease#35]
In case a regular dependency can be easily updated, we could:
- Update the changelog with an robot-like description :yum:
- Trigger a `version("patch")`
- Release the new version (and commit the updated files (changelog and package [-lock])

**Comment by t1m0thyj** [comment]
@zFernand0 Do we still want this for updating Imperative in Zowe CLI or plugin repos? Or does the [`npmUpdate` script](https://github.com/zowe-actions/octorelease/blob/master/packages/run-script/scripts/npmUpdate.ts) suffice for updating dependencies?

**Comment by zFernand0** [comment]
Yeah, the `npmUpdate` script should be fine.
